//
// AIM defines
//

const AIMHISTORYFILE = "BINARYDATA\\AimHist.edt";
const AIM_HISTORY_LINE_SIZE = 400 * 2;

const MAX_NUMBER_MERCS = 40;

const NUM_AIM_SCREENS = 6;

const IMAGE_OFFSET_X = LAPTOP_SCREEN_UL_X; // 111
const IMAGE_OFFSET_Y = LAPTOP_SCREEN_WEB_UL_Y; // 24

const AIM_LOGO_TEXT_X = 175;
const AIM_LOGO_TEXT_Y = 77 + LAPTOP_SCREEN_WEB_DELTA_Y + 4;
const AIM_LOGO_TEXT_WIDTH = 360;

// Aim Symbol 203, 51
const AIM_SYMBOL_SIZE_X = 203;
const AIM_SYMBOL_SIZE_Y = 51;

// 262, 28
const AIM_SYMBOL_X = IMAGE_OFFSET_X + 149;
const AIM_SYMBOL_Y = IMAGE_OFFSET_Y + 3;
const AIM_SYMBOL_WIDTH = 203;
const AIM_SYMBOL_HEIGHT = 51;

// RustBackGround
const RUSTBACKGROUND_SIZE_X = 125;
const RUSTBACKGROUND_SIZE_Y = 100;

const RUSTBACKGROUND_1_X = IMAGE_OFFSET_X;
const RUSTBACKGROUND_1_Y = IMAGE_OFFSET_Y;

// Bottom Buttons
const NUM_AIM_BOTTOMBUTTONS = 6;
const BOTTOM_BUTTON_START_WIDTH = 75;
const BOTTOM_BUTTON_START_HEIGHT = 18;
const BOTTOM_BUTTON_START_X = LAPTOP_SCREEN_UL_X + 25;
const BOTTOM_BUTTON_START_Y = LAPTOP_SCREEN_WEB_LR_Y - BOTTOM_BUTTON_START_HEIGHT - 3;
const BOTTOM_BUTTON_AMOUNT = NUM_AIM_SCREENS;
const BOTTOM_BUTTON_GAP = 0;
const BOTTOM_BUTTON_TEXT_Y = BOTTOM_BUTTON_START_Y + 6;
const BOTTOM_BUTTON_END_X = BOTTOM_BUTTON_START_X + BOTTOM_BUTTON_START_WIDTH * 6;
const BOTTOM_BUTTON_END_Y = BOTTOM_BUTTON_START_Y + BOTTOM_BUTTON_START_HEIGHT;

const AIM_FONT10ROMAN = () => FONT10ROMAN();
const AIM_FONT12ROMAN = () => FONT12ROMAN();
const AIM_FONT14SANSERIF = () => FONT14SANSERIF();
const AIM_LOGO_FONT = () => FONT10ARIAL();
const AIM_COPYRIGHT_FONT = () => FONT10ARIAL();
const AIM_WARNING_FONT = () => FONT12ARIAL();
const AIM_FONT12ARIAL = () => FONT12ARIAL();
const AIM_FONT_MCOLOR_WHITE = FONT_MCOLOR_WHITE;
const AIM_FONT_MCOLOR_DKRED = FONT_MCOLOR_RED;
const AIM_GREEN = 157;
const AIM_MAINTITLE_COLOR = AIM_GREEN;
const AIM_MAINTITLE_FONT = () => FONT14ARIAL();
const AIM_BUTTON_ON_COLOR = FONT_MCOLOR_DKWHITE;
const AIM_BUTTON_OFF_COLOR = 138;
const AIM_BUTTON_DISABLED_COLOR = 141;
const AIM_CONTENTBUTTON_WIDTH = 205;
const AIM_CONTENTBUTTON_HEIGHT = 19;
const AIM_FONT_GOLD = 170;

const enum Enum63 {
  AIM_SLOGAN,
  AIM_WARNING_1,
  AIM_WARNING_2,
  AIM_COPYRIGHT_1,
  AIM_COPYRIGHT_2,
  AIM_COPYRIGHT_3,
}
