//#include "LaptopSave.h"

const BOBBYRDESCFILE = "BINARYDATA\\BrayDesc.edt";

const BOBBYR_ITEM_DESC_NAME_SIZE = 160;
const BOBBYR_ITEM_DESC_INFO_SIZE = 640;
const BOBBYR_ITEM_DESC_FILE_SIZE = 800;

const BOBBYR_USED_ITEMS = 0xFFFFFFFF;

const BOBBYR_GUNS_BUTTON_FONT = () => FONT10ARIAL();
const BOBBYR_GUNS_TEXT_COLOR_ON = FONT_NEARBLACK;
const BOBBYR_GUNS_TEXT_COLOR_OFF = FONT_NEARBLACK;
//#define		BOBBYR_GUNS_TEXT_COLOR_ON					FONT_MCOLOR_DKWHITE
//#define		BOBBYR_GUNS_TEXT_COLOR_OFF				FONT_MCOLOR_WHITE

const BOBBYR_GUNS_SHADOW_COLOR = 169;

const BOBBYR_NO_ITEMS = 65535;
