namespace ja2 {

//#include "LaptopSave.h"

export const BOBBYRDESCFILE = "BINARYDATA\\BrayDesc.edt";

export const BOBBYR_ITEM_DESC_NAME_SIZE = 160;
export const BOBBYR_ITEM_DESC_INFO_SIZE = 640;
export const BOBBYR_ITEM_DESC_FILE_SIZE = 800;

export const BOBBYR_USED_ITEMS = 0xFFFFFFFF;

export const BOBBYR_GUNS_BUTTON_FONT = () => FONT10ARIAL();
export const BOBBYR_GUNS_TEXT_COLOR_ON = FONT_NEARBLACK;
export const BOBBYR_GUNS_TEXT_COLOR_OFF = FONT_NEARBLACK;
//#define		BOBBYR_GUNS_TEXT_COLOR_ON					FONT_MCOLOR_DKWHITE
//#define		BOBBYR_GUNS_TEXT_COLOR_OFF				FONT_MCOLOR_WHITE

export const BOBBYR_GUNS_SHADOW_COLOR = 169;

export const BOBBYR_NO_ITEMS = 65535;

}
