namespace ja2 {

// extern BOOLEAN fIMPCompletedFlag;

export const enum Enum71 {
  IMP_HOME_PAGE,
  IMP_BEGIN,
  IMP_FINISH,
  IMP_MAIN_PAGE,
  IMP_PERSONALITY,
  IMP_PERSONALITY_QUIZ,
  IMP_PERSONALITY_FINISH,
  IMP_ATTRIBUTE_ENTRANCE,
  IMP_ATTRIBUTE_PAGE,
  IMP_ATTRIBUTE_FINISH,
  IMP_PORTRAIT,
  IMP_VOICE,
  IMP_ABOUT_US,
  IMP_CONFIRM,

  IMP_NUM_PAGES,
}

export const COST_OF_PROFILE = 3000;

}
