namespace ja2 {

export const FLORIST_BUTTON_TEXT_FONT = () => FONT14ARIAL();
export const FLORIST_BUTTON_TEXT_UP_COLOR = 2;
export const FLORIST_BUTTON_TEXT_DOWN_COLOR = 2;
export const FLORIST_BUTTON_TEXT_SHADOW_COLOR = 128;

}
