const PLAYER_GENERATED_CHARACTER_ID = 51;
const ATTITUDE_LIST_SIZE = 20;
const NUMBER_OF_PLAYER_PORTRAITS = 16;

extern STR8 pPlayerSelectedFaceFileNames[NUMBER_OF_PLAYER_PORTRAITS];
extern STR8 pPlayerSelectedBigFaceFileNames[NUMBER_OF_PLAYER_PORTRAITS];
