// the functions

// graphical handles

extern UINT32 guiBACKGROUND;
extern UINT32 guiIMPSYMBOL;
extern UINT32 guiBEGININDENT;
extern UINT32 guiACTIVATIONINDENT;
extern UINT32 guiFRONTPAGEINDENT;
extern UINT32 guiFULLNAMEINDENT;
extern UINT32 guiGENDERINDENT;
extern UINT32 guiSMALLFRAME;
extern UINT32 guiANALYSE;
extern UINT32 guiATTRIBUTEGRAPH;
extern UINT32 guiATTRIBUTEGRAPHBAR;
extern UINT32 guiSMALLSILHOUETTE;
extern UINT32 guiLARGESILHOUETTE;
extern UINT32 guiPORTRAITFRAME;
extern UINT32 guiATTRIBUTEFRAME;
extern UINT32 guiATTRIBUTESCREENINDENT1;
extern UINT32 guiATTRIBUTESCREENINDENT2;
extern UINT32 guiSLIDERBAR;
