export const INS_FONT_COLOR = 2;
export const INS_FONT_COLOR_RED = FONT_MCOLOR_RED;
export const INS_FONT_BIG = () => FONT14ARIAL();
export const INS_FONT_MED = () => FONT12ARIAL();
export const INS_FONT_SMALL = () => FONT10ARIAL();

export const INS_FONT_BTN_COLOR = FONT_MCOLOR_WHITE;
export const INS_FONT_BTN_SHADOW_COLOR = 2;

export const INS_FONT_SHADOW = FONT_MCOLOR_WHITE;

export const INSURANCE_BULLET_TEXT_OFFSET_X = 21;

export const INS_INFO_LEFT_ARROW_BUTTON_X = 71 + LAPTOP_SCREEN_UL_X;
export const INS_INFO_LEFT_ARROW_BUTTON_Y = 354 + LAPTOP_SCREEN_WEB_UL_Y;

export const INS_INFO_RIGHT_ARROW_BUTTON_X = 409 + LAPTOP_SCREEN_UL_X;
export const INS_INFO_RIGHT_ARROW_BUTTON_Y = INS_INFO_LEFT_ARROW_BUTTON_Y;
