const enum Enum220 {
  STANCEUP_BUTTON = 0,
  UPDOWN_BUTTON,
  CLIMB_BUTTON,
  STANCEDOWN_BUTTON,
  HANDCURSOR_BUTTON,
  PREVMERC_BUTTON,
  NEXTMERC_BUTTON,
  OPTIONS_BUTTON,
  BURSTMODE_BUTTON,
  LOOK_BUTTON,
  TALK_BUTTON,
  MUTE_BUTTON,
  SM_DONE_BUTTON,
  SM_MAP_SCREEN_BUTTON,
  NUM_SM_BUTTONS,
}

const enum Enum221 {
  TEAM_DONE_BUTTON = 0,
  TEAM_MAP_SCREEN_BUTTON,
  CHANGE_SQUAD_BUTTON,
  NUM_TEAM_BUTTONS,
}

const NEW_ITEM_CYCLE_COUNT = 19;
const NEW_ITEM_CYCLES = 4;
const NUM_TEAM_SLOTS = 6;

const PASSING_ITEM_DISTANCE_OKLIFE = 3;
const PASSING_ITEM_DISTANCE_NOTOKLIFE = 2;

const SHOW_LOCATOR_NORMAL = 1;
const SHOW_LOCATOR_FAST = 2;

interface TEAM_PANEL_SLOTS_TYPE {
  ubID: UINT8;
  fOccupied: boolean;
}

// void DisableSMPpanelButtonsWhenInShopKeeperInterface( );
