const MAX_UICOMPOSITES = 4;

const INTERFACE_START_Y = 360;
const INV_INTERFACE_START_Y = 340;

const INTERFACE_START_X = 0;

// FLASH PORTRAIT CODES
const FLASH_PORTRAIT_STOP = 0;
const FLASH_PORTRAIT_START = 1;
const FLASH_PORTRAIT_WAITING = 2;
const FLASH_PORTRAIT_DELAY = 150;

// FLASH PORTRAIT PALETTE IDS
const FLASH_PORTRAIT_NOSHADE = 0;
const FLASH_PORTRAIT_STARTSHADE = 1;
const FLASH_PORTRAIT_ENDSHADE = 2;
const FLASH_PORTRAIT_DARKSHADE = 3;
const FLASH_PORTRAIT_GRAYSHADE = 4;
const FLASH_PORTRAIT_LITESHADE = 5;

// GLOBAL DEFINES FOR SOME UI FLAGS
const ARROWS_HIDE_UP = 0x00000002;
const ARROWS_HIDE_DOWN = 0x00000004;
const ARROWS_SHOW_UP_BESIDE = 0x00000008;
const ARROWS_SHOW_DOWN_BESIDE = 0x00000020;
const ARROWS_SHOW_UP_ABOVE_Y = 0x00000040;
const ARROWS_SHOW_DOWN_BELOW_Y = 0x00000080;
const ARROWS_SHOW_DOWN_BELOW_G = 0x00000200;
const ARROWS_SHOW_DOWN_BELOW_YG = 0x00000400;
const ARROWS_SHOW_DOWN_BELOW_GG = 0x00000800;
const ARROWS_SHOW_UP_ABOVE_G = 0x00002000;
const ARROWS_SHOW_UP_ABOVE_YG = 0x00004000;
const ARROWS_SHOW_UP_ABOVE_GG = 0x00008000;
const ARROWS_SHOW_UP_ABOVE_YY = 0x00020000;
const ARROWS_SHOW_DOWN_BELOW_YY = 0x00040000;
const ARROWS_SHOW_UP_ABOVE_CLIMB = 0x00080000;
const ARROWS_SHOW_UP_ABOVE_CLIMB2 = 0x00400000;
const ARROWS_SHOW_UP_ABOVE_CLIMB3 = 0x00800000;
const ARROWS_SHOW_DOWN_CLIMB = 0x02000000;

const ROOF_LEVEL_HEIGHT = 50;

const LOCATEANDSELECT_MERC = 1;
const LOCATE_MERC_ONCE = 2;

// Interface level enums
const enum Enum214 {
  I_GROUND_LEVEL,
  I_ROOF_LEVEL,
  I_NUMLEVELS,
}

const DRAW_RED_BAR = 1;
const DRAW_BLUE_BAR = 2;
const DRAW_ERASE_BAR = 3;

BOOLEAN gfSwitchPanel;
BOOLEAN gfUIStanceDifferent;
UINT8 gbNewPanel;
UINT8 gubNewPanelParam;
INT16 gsCurInterfacePanel;

UINT32 guiRENDERBUFFER;
UINT32 guiCLOSE;
UINT32 guiDEAD;
UINT32 guiHATCH;
UINT32 guiINTEXT;
UINT32 guiGUNSM;
UINT32 guiP1ITEMS;
UINT32 guiP2ITEMS;
UINT32 guiP3ITEMS;
UINT32 guiCOMPANEL;
extern UINT32 guiCOMPANELB;
UINT32 guiRADIO;
UINT32 guiPORTRAITICONS;
UINT32 guiBURSTACCUM;
UINT32 guiITEMPOINTERHATCHES;

MOUSE_REGION gViewportRegion;
MOUSE_REGION gRadarRegion;
MOUSE_REGION gBottomPanalRegion;

const MOVEMENT_MENU_LOOK = 1;
const MOVEMENT_MENU_ACTIONC = 2;
const MOVEMENT_MENU_HAND = 3;
const MOVEMENT_MENU_TALK = 4;
const MOVEMENT_MENU_RUN = 5;
const MOVEMENT_MENU_WALK = 6;
const MOVEMENT_MENU_SWAT = 7;
const MOVEMENT_MENU_PRONE = 8;

const DIRTYLEVEL0 = 0;
const DIRTYLEVEL1 = 1;
const DIRTYLEVEL2 = 2;

const enum Enum215 {
  SM_PANEL,
  TEAM_PANEL,
  NUM_UI_PANELS,
}

BOOLEAN fInterfacePanelDirty;
BOOLEAN gfPausedTacticalRenderFlags;
BOOLEAN gfPausedTacticalRenderInterfaceFlags;
INT16 gsInterfaceLevel;
BOOLEAN gfInMovementMenu;

UINT16 gusUIOldSelectedSoldier;

INT32 giUIMessageOverlay;
UINT32 guiUIMessageTime;

const enum Enum216 {
  NO_MESSAGE,
  COMPUTER_TURN_MESSAGE,
  COMPUTER_INTERRUPT_MESSAGE,
  PLAYER_INTERRUPT_MESSAGE,
  MILITIA_INTERRUPT_MESSAGE,
  AIR_RAID_TURN_MESSAGE,
  PLAYER_TURN_MESSAGE,
}
