const TB_BREATH_RECOVER_MODIFIER = 1;
const TB_BREATH_DEDUCT_MODIFIER = 1.25;

const RT_NEXT_BLEED_MODIFIER = 0.5;
const RT_FIRST_AID_GAIN_MODIFIER = 12;

const NUM_REAL_SEC_PER_TACTICAL_TURN = 5000;

const RT_COMPRESSION_TACTICAL_TURN_MODIFIER = 10;
