namespace ja2 {

export const enum Enum255 {
  NO_CHECK = 0,
  LOCKPICKING_CHECK,
  ELECTRONIC_LOCKPICKING_CHECK,
  ATTACHING_DETONATOR_CHECK,
  ATTACHING_REMOTE_DETONATOR_CHECK,
  PLANTING_BOMB_CHECK,
  PLANTING_REMOTE_BOMB_CHECK,
  OPEN_WITH_CROWBAR,
  SMASH_DOOR_CHECK,
  DISARM_TRAP_CHECK,
  UNJAM_GUN_CHECK,
  NOTICE_DART_CHECK,
  LIE_TO_QUEEN_CHECK,
  ATTACHING_SPECIAL_ITEM_CHECK,
  ATTACHING_SPECIAL_ELECTRONIC_ITEM_CHECK,
  DISARM_ELECTRONIC_TRAP_CHECK,
}

}
