namespace ja2 {

// RADAR WINDOW DEFINES
export const RADAR_WINDOW_X = 543;
export const RADAR_WINDOW_TM_Y = INTERFACE_START_Y + 13;
const RADAR_WINDOW_SM_Y = INV_INTERFACE_START_Y + 13;
export const RADAR_WINDOW_WIDTH = 88;
export const RADAR_WINDOW_HEIGHT = 44;

}
