export const NOTHING_BLOCKING = 0;
export const BLOCKING_REDUCE_RANGE = 1;
export const BLOCKING_NEXT_TILE = 10;
export const BLOCKING_TOPLEFT_WINDOW = 30;
export const BLOCKING_TOPRIGHT_WINDOW = 40;
export const BLOCKING_TOPLEFT_DOOR = 50;
export const BLOCKING_TOPRIGHT_DOOR = 60;
export const FULL_BLOCKING = 70;
export const BLOCKING_TOPLEFT_OPEN_WINDOW = 90;
export const BLOCKING_TOPRIGHT_OPEN_WINDOW = 100;

// ATE: Increased to allow corpses to not collide with soldiers
// 100 == MAX_CORPSES
export const INVALID_STRUCTURE_ID = (TOTAL_SOLDIERS + 100);
export const IGNORE_PEOPLE_STRUCTURE_ID = (TOTAL_SOLDIERS + 101);

export const STRUCTURE_DAMAGE_EXPLOSION = 1;
export const STRUCTURE_DAMAGE_GUNFIRE = 2;

// Material armour type enumeration
export const enum Enum309 {
  MATERIAL_NOTHING,
  MATERIAL_WOOD_WALL,
  MATERIAL_PLYWOOD_WALL,
  MATERIAL_LIVE_WOOD,
  MATERIAL_LIGHT_VEGETATION,
  MATERIAL_FURNITURE,
  MATERIAL_PORCELAIN,
  MATERIAL_CACTUS,
  MATERIAL_NOTUSED1,
  MATERIAL_NOTUSED2,

  MATERIAL_NOTUSED3,
  MATERIAL_STONE,
  MATERIAL_CONCRETE1,
  MATERIAL_CONCRETE2,
  MATERIAL_ROCK,
  MATERIAL_RUBBER,
  MATERIAL_SAND,
  MATERIAL_CLOTH,
  MATERIAL_SANDBAG,
  MATERIAL_NOTUSED5,

  MATERIAL_NOTUSED6,
  MATERIAL_LIGHT_METAL,
  MATERIAL_THICKER_METAL,
  MATERIAL_HEAVY_METAL,
  MATERIAL_INDESTRUCTABLE_STONE,
  MATERIAL_INDESTRUCTABLE_METAL,
  MATERIAL_THICKER_METAL_WITH_SCREEN_WINDOWS,
  NUM_MATERIAL_TYPES,
}
