const NUM_MOUSE_LEVELS = 2;

let gsMouseGlobalYOffsets: INT16[] /* [NUM_MOUSE_LEVELS] */ = [
  0,
  50,
];

let CursorFileDatabase: CursorFileData[] /* [] */ = [
  [ "CURSORS\\cursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_targ.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\cur_tagr.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\targblak.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\cur_bst.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\cur_rbst.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\burstblk.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],
  [ "CURSORS\\cur_tr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_trw.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_tb.sti", FALSE, 0, ANIMATED_CURSOR, 7, null ],

  [ "CURSORS\\punch.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],
  [ "CURSORS\\punchr.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],
  [ "CURSORS\\cur_run.sti", FALSE, 0, ANIMATED_CURSOR, 10, null ],
  [ "CURSORS\\cur_walk.sti", FALSE, 0, ANIMATED_CURSOR, 10, null ],
  [ "CURSORS\\cur_swat.sti", FALSE, 0, ANIMATED_CURSOR, 10, null ],
  [ "CURSORS\\cur_pron.sti", FALSE, 0, ANIMATED_CURSOR, 10, null ],
  [ "CURSORS\\grabsr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\grabs.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\stab.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],
  [ "CURSORS\\stabr.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],

  [ "CURSORS\\cross1.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],
  [ "CURSORS\\cross2.sti", FALSE, 0, ANIMATED_CURSOR, 6, null ],
  [ "LAPTOP\\FingerCursor.sti", FALSE, 0, 0, 0, null ],
  [ "LAPTOP\\LapTopCursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\ibeam.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_look.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_talk.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_talkb.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_talkr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_exit.sti", FALSE, 0, 0, 0, null ],

  [ "CURSORS\\VehicleCursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\WalkingCursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\que.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\chopper.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\check.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_try.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\wirecut.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\wirecutr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\bullet_g.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\bullet_d.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\ibeamWhite.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\throwg.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\throwb.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\throwr.sti", FALSE, 0, 0, 0, null ],
  [ "", FALSE, 0, USE_EXTERN_VO_CURSOR | USE_OUTLINE_BLITTER, 0, null ],
  [ "CURSORS\\bombg.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\bombr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\remoteg.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\remoter.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\steering.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_car.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_wait.sti", FALSE, 0, 0, 0, null ],

  // Tactical GUI cursors
  [ "CURSORS\\singlecursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\groupcursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\singledcursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\groupdcursor.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\repair.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\repairr.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\jar_cur.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\jar_cur_red.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_x.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\can_01.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\can_02.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\cur_swit.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\bullseye.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\deadleap.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\can_01.sti", FALSE, 0, 0, 0, null ],
  [ "CURSORS\\can_02.sti", FALSE, 0, 0, 0, null ],
];

function RaiseMouseToLevel(bLevel: INT8): void {
  gsGlobalCursorYOffset = gsMouseGlobalYOffsets[bLevel];
}

let CursorDatabase: CursorData[] /* [] */ = [
  [ [ Enum318.C_MISC, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, 0, 0, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_ACTIONMODE, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  // TARGET ( NORMAL W/ RINGS )
  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 5, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 7, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 8, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 4, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  // TARGET WITH WHITE RINGS
  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_TWRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_TWRINGS, 4, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  // TARGET RED CURSOR
  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  // TARGET BLACK CURSOR
  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_BLACKTARGET, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  // TARGET DARK BLACK CURSOR
  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  // TARGET RED CURSOR

  [ [ Enum318.C_TARGMODEBURSTRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TARGMODEBURSTBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], 5, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_TARGMODEBURST, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TARGMODEBURSTRED, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TARGMODEBURSTBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_PUNCHGRAY, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_PUNCHRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_RUN1, 0, 0, CENTER_SUBCURSOR, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, 20, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_WALK1, 0, 0, CENTER_SUBCURSOR, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, 20, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_SWAT1, 0, 0, CENTER_SUBCURSOR, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, 10, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_PRONE1, 0, 0, CENTER_SUBCURSOR, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, 10, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 0, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_GRAB1, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 0, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_GRAB2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_KNIFE1, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_KNIFE2, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_CROSS1, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_CROSS2, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],
  [ [ Enum318.C_WWW, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, 0, 0, 0, 0, 0, 0 ],
  [ [ Enum318.C_LAPTOPSCREEN, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, 0, 0, 0, 0, 0, 0 ],
  [ [ Enum318.C_IBEAM, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_LOOK, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_TALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_BLACKTALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_REDTALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  // Exit arrows
  [ [ Enum318.C_EXITARROWS, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, TOP_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 1, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 2, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, RIGHT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 3, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, LEFT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 4, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, TOP_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 5, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 6, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, RIGHT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 7, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, LEFT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 8, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, TOP_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 9, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 10, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, RIGHT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 11, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, LEFT_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_STRATVEH, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_STRATFOOT, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_INVALIDACTION, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],
  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_CHOPPER, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_ACTIONMODE, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_TARGMODEBURST, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TARGMODEBURSTBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_TALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_BLACKTALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_REDTALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_BLACKTALK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_CHECKMARK, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 5, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_ACTIONMODERED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_EXITARROWS, 12, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 13, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_EXITARROWS, 14, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_WIRECUTR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_WIRECUT, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_RELOAD, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_ACTIONMODEBLACK, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_RELOADR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  [ [ Enum318.C_IBEAM_WHITE, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_THROWG, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_THROWG, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH, 0 ],

  // THROW CURSORS W/ RINGS
  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 5, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 7, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 8, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 4, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  // TARGET WITH WHITE RINGS
  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_TWRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_TWRINGS, 4, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  // YELLOW RINGS
  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 5, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 1, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 2, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  [ [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_YELLOWRINGS, 3, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_SUB_CONDITIONALLY, 0 ],

  // ITEM THROW ONES...
  [ [ Enum318.C_ITEMTHROW, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWG, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 0, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_ITEMTHROW, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 3, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_ITEMTHROW, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWG, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_THROWB, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], 4, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH2, 0 ],

  [ [ Enum318.C_ITEMTHROW, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, CURSOR_TO_FLASH2, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_BOMB_GREY, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_BOMB_RED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_REMOTE_GREY, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_REMOTE_RED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_ENTERV, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_MOVEV, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_WAIT, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, DELAY_START_CURSOR, 0 ],

  // Tactical Placement GUI cursors
  [ [ Enum318.C_PLACEMERC, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],
  [ [ Enum318.C_PLACEGROUP, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],
  [ [ Enum318.C_DPLACEMERC, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_DPLACEGROUP, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, BOTTOM_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_REPAIR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_REPAIRR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_JAR, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_JARRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_CAN, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_CANRED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_X, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_WAIT, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_EXCHANGE, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_BULLSEYE, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 1, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_JUMPOVER, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_FUEL, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],

  [ [ Enum318.C_TRINGS, 6, 0, HIDE_SUBCURSOR, HIDE_SUBCURSOR ], [ Enum318.C_FUEL_RED, 0, 0, CENTER_SUBCURSOR, CENTER_SUBCURSOR ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], 2, CENTER_CURSOR, CENTER_CURSOR, 0, 0, 0, 0 ],
];

function InitCursors(): void {
  InitCursorDatabase(CursorFileDatabase, CursorDatabase, Enum318.NUM_CURSOR_FILES);

  SetMouseBltHook(BltJA2CursorData);
}

function HandleAnimatedCursors(): void {
  if (COUNTERDONE(Enum386.CURSORCOUNTER)) {
    RESETCOUNTER(Enum386.CURSORCOUNTER);

    if (gViewportRegion.uiFlags & MSYS_MOUSE_IN_AREA) {
      UpdateAnimatedCursorFrames(gViewportRegion.Cursor);
      SetCurrentCursorFromDatabase(gViewportRegion.Cursor);
    }

    if (gDisableRegion.uiFlags & MSYS_MOUSE_IN_AREA) {
      UpdateAnimatedCursorFrames(gDisableRegion.Cursor);
      SetCurrentCursorFromDatabase(gDisableRegion.Cursor);
    }

    if (gUserTurnRegion.uiFlags & MSYS_MOUSE_IN_AREA) {
      UpdateAnimatedCursorFrames(gUserTurnRegion.Cursor);
      SetCurrentCursorFromDatabase(gUserTurnRegion.Cursor);
    }
  }

  if (COUNTERDONE(Enum386.CURSORFLASHUPDATE)) {
    RESETCOUNTER(Enum386.CURSORFLASHUPDATE);

    if (gViewportRegion.uiFlags & MSYS_MOUSE_IN_AREA) {
      UpdateFlashingCursorFrames(gViewportRegion.Cursor);
      SetCurrentCursorFromDatabase(gViewportRegion.Cursor);
    }
  }
}

function BltJA2CursorData(): void {
  if ((gViewportRegion.uiFlags & MSYS_MOUSE_IN_AREA)) {
    DrawMouseText();
  }
}

function DrawMouseText(): void {
  let pStr: INT16[] /* [512] */;
  let sX: INT16;
  let sY: INT16;
  /* static */ let fShow: BOOLEAN = FALSE;
  /* static */ let fHoldInvalid: BOOLEAN = TRUE;

  // EnterMutex(MOUSE_BUFFER_MUTEX, __LINE__, __FILE__);

  if (gfUIBodyHitLocation) {
    // Set dest for gprintf to be different
    SetFontDestBuffer(MOUSE_BUFFER, 0, 0, 64, 64, FALSE);

    FindFontCenterCoordinates(0, 0, gsCurMouseWidth, gsCurMouseHeight, gzLocation, TINYFONT1(), addressof(sX), addressof(sY));
    SetFont(TINYFONT1());

    SetFontBackground(FONT_MCOLOR_BLACK);
    SetFontForeground(FONT_MCOLOR_WHITE);

    mprintf(sX, sY + 12, gzLocation);
    // reset
    SetFontDestBuffer(FRAME_BUFFER, 0, 0, 640, 480, FALSE);
  }

  if (gfUIIntTileLocation) {
    // Set dest for gprintf to be different
    SetFontDestBuffer(MOUSE_BUFFER, 0, 0, 64, 64, FALSE);

    FindFontCenterCoordinates(0, 0, gsCurMouseWidth, gsCurMouseHeight, gzIntTileLocation, TINYFONT1(), addressof(sX), addressof(sY));
    SetFont(TINYFONT1());

    SetFontBackground(FONT_MCOLOR_BLACK);
    SetFontForeground(FONT_MCOLOR_WHITE);

    mprintf(sX, sY + 6, gzIntTileLocation);
    // reset
    SetFontDestBuffer(FRAME_BUFFER, 0, 0, 640, 480, FALSE);
  }

  if (gfUIIntTileLocation2) {
    // Set dest for gprintf to be different
    SetFontDestBuffer(MOUSE_BUFFER, 0, 0, 64, 64, FALSE);

    FindFontCenterCoordinates(0, 0, gsCurMouseWidth, gsCurMouseHeight, gzIntTileLocation2, TINYFONT1(), addressof(sX), addressof(sY));
    SetFont(TINYFONT1());

    SetFontBackground(FONT_MCOLOR_BLACK);
    SetFontForeground(FONT_MCOLOR_WHITE);

    mprintf(sX, sY - 2, gzIntTileLocation2);
    // reset
    SetFontDestBuffer(FRAME_BUFFER, 0, 0, 640, 480, FALSE);
  }

  // if ( ( ( gTacticalStatus.uiFlags & TURNBASED ) && ( gTacticalStatus.uiFlags & INCOMBAT ) ) )
  {
    if (gfUIDisplayActionPoints) {
      if (gfUIDisplayActionPointsInvalid) {
        if (!fHoldInvalid) {
          if (COUNTERDONE(Enum386.INVALID_AP_HOLD)) {
            RESETCOUNTER(Enum386.INVALID_AP_HOLD);
            RESETCOUNTER(Enum386.CURSORFLASH);

            fShow = !fShow;
            fHoldInvalid = !fHoldInvalid;
          }
        } else {
          if (COUNTERDONE(Enum386.CURSORFLASH)) {
            RESETCOUNTER(Enum386.CURSORFLASH);
            RESETCOUNTER(Enum386.INVALID_AP_HOLD);

            fShow = !fShow;
            fHoldInvalid = !fHoldInvalid;
          }
        }
      } else {
        fShow = TRUE;
        fHoldInvalid = FALSE;
      }

      // Set dest for gprintf to be different
      SetFontDestBuffer(MOUSE_BUFFER, 0, 0, 64, 64, FALSE);

      swprintf(pStr, "%d", gsCurrentActionPoints);

      if (gfUIDisplayActionPointsCenter) {
        FindFontCenterCoordinates(0, 0, gsCurMouseWidth, gsCurMouseHeight, pStr, TINYFONT1(), addressof(sX), addressof(sY));
      } else {
        FindFontCenterCoordinates(gUIDisplayActionPointsOffX, gUIDisplayActionPointsOffY, 1, 1, pStr, TINYFONT1(), addressof(sX), addressof(sY));
      }

      SetFont(TINYFONT1());

      if (fShow) {
        if (gfUIDisplayActionPointsInvalid) {
          SetFontBackground(FONT_MCOLOR_BLACK);
          SetFontForeground(141);
          // SetFontShadow( NO_SHADOW );
          SetFontShadow(DEFAULT_SHADOW);
        } else {
          SetFontBackground(FONT_MCOLOR_BLACK);
          SetFontForeground(FONT_MCOLOR_WHITE);
          SetFontShadow(DEFAULT_SHADOW);
        }
      } else {
        gfUIDisplayActionPointsBlack = TRUE;
      }

      if (gfUIDisplayActionPointsBlack) {
        SetFontForeground(FONT_MCOLOR_WHITE);
        SetFontShadow(DEFAULT_SHADOW);
      }

      mprintf(sX, sY, "%d", gsCurrentActionPoints);
      // mprintf( sX, sY, L"%d %d", sX, sY );

      // LeaveMutex(MOUSE_BUFFER_MUTEX, __LINE__, __FILE__);

      SetFontShadow(DEFAULT_SHADOW);

      // reset
      SetFontDestBuffer(FRAME_BUFFER, 0, 0, 640, 480, FALSE);
    }
  }
}

function UpdateAnimatedCursorFrames(uiCursorIndex: UINT32): void {
  let pCurData: Pointer<CursorData>;
  let pCurImage: Pointer<CursorImage>;
  let cnt: UINT32;

  if (uiCursorIndex != VIDEO_NO_CURSOR) {
    pCurData = addressof(CursorDatabase[uiCursorIndex]);

    for (cnt = 0; cnt < pCurData.value.usNumComposites; cnt++) {
      pCurImage = addressof(pCurData.value.Composites[cnt]);

      if (CursorFileDatabase[pCurImage.value.uiFileIndex].ubFlags & ANIMATED_CURSOR) {
        pCurImage.value.uiCurrentFrame++;

        if (pCurImage.value.uiCurrentFrame == CursorFileDatabase[pCurImage.value.uiFileIndex].ubNumberOfFrames) {
          pCurImage.value.uiCurrentFrame = 0;
        }
      }
    }
  }
}

function UpdateFlashingCursorFrames(uiCursorIndex: UINT32): void {
  let pCurData: Pointer<CursorData>;

  if (uiCursorIndex != VIDEO_NO_CURSOR) {
    pCurData = addressof(CursorDatabase[uiCursorIndex]);

    if ((pCurData.value.bFlags & (CURSOR_TO_FLASH | CURSOR_TO_FLASH2))) {
      pCurData.value.bFlashIndex = !pCurData.value.bFlashIndex;

      // Should we play a sound?
      if (pCurData.value.bFlags & (CURSOR_TO_PLAY_SOUND)) {
        if (pCurData.value.bFlashIndex) {
          PlayJA2Sample(Enum330.TARGET_OUT_OF_RANGE, RATE_11025, MIDVOLUME, 1, MIDDLEPAN);
        }
      }
    }
  }
}

function SetCursorSpecialFrame(uiCursor: UINT32, ubFrame: UINT8): void {
  CursorDatabase[uiCursor].bFlashIndex = ubFrame;
}

function SetCursorFlags(uiCursor: UINT32, ubFlags: UINT8): void {
  CursorDatabase[uiCursor].bFlags |= ubFlags;
}

function RemoveCursorFlags(uiCursor: UINT32, ubFlags: UINT8): void {
  CursorDatabase[uiCursor].bFlags &= (~ubFlags);
}

function GetCursorFileVideoObject(uiCursorFile: UINT32): HVOBJECT {
  return CursorFileDatabase[uiCursorFile].hVObject;
}

function SyncPairedCursorFrames(uiSrcIndex: UINT32, uiDestIndex: UINT32): void {
}
