const enum Enum327 {
  MARIMBAD2_MUSIC,
  MENUMIX_MUSIC,
  NOTHING_A_MUSIC,
  NOTHING_B_MUSIC,
  NOTHING_C_MUSIC,
  NOTHING_D_MUSIC,
  TENSOR_A_MUSIC,
  TENSOR_B_MUSIC,
  TENSOR_C_MUSIC,
  TRIUMPH_MUSIC,
  DEATH_MUSIC,
  BATTLE_A_MUSIC,
  BATTLE_B_MUSIC, // same as tensor B
  CREEPY_MUSIC,
  CREATURE_BATTLE_MUSIC,
  NUM_MUSIC,
}

const enum Enum328 {
  MUSIC_NONE,
  MUSIC_RESTORE,
  MUSIC_MAIN_MENU,
  MUSIC_TACTICAL_NOTHING,
  MUSIC_TACTICAL_ENEMYPRESENT,
  MUSIC_TACTICAL_BATTLE,
  MUSIC_TACTICAL_VICTORY,
  MUSIC_TACTICAL_DEATH,
  MUSIC_LAPTOP,
}
