const enum Enum160 {
  END_OF_PLAYERS_FIRST_BATTLE,
  DRASSEN_LIBERATED,
  CAMBRIA_LIBERATED,
  ALMA_LIBERATED,
  GRUMM_LIBERATED,
  CHITZENA_LIBERATED,
  NW_SAM,
  NE_SAM,
  CENTRAL_SAM,
  FLOWERS,
  LOST_TOWN,
  INTERROGATION,
  CREATURES,
  KILL_CHOPPER,
  AWOL_SCIENTIST,
  OUTSKIRTS_MEDUNA,
  BALIME_LIBERATED,
  NUM_MEANWHILES,
}

interface MEANWHILE_DEFINITION {
  sSectorX: INT16;
  sSectorY: INT16;
  usTriggerEvent: UINT16;

  ubMeanwhileID: UINT8;
  ubNPCNumber: UINT8;
}

extern MEANWHILE_DEFINITION gCurrentMeanwhileDef;
extern MEANWHILE_DEFINITION gMeanwhileDef[NUM_MEANWHILES];
extern BOOLEAN gfMeanwhileScheduled;
extern BOOLEAN gfMeanwhileTryingToStart;
extern BOOLEAN gfInMeanwhile;
extern UINT32 uiMeanWhileFlags;
